name: build RZL CodingContest Environment

on:
  push:
    branches: 
      - main
    paths:
      - .github/workflows/build.yml
      - ContestProject/**
      - ContestProjectTests/**
  pull_request:
    paths:
      - .github/workflows/build.yml
      - ContestProject/**
      - ContestProjectTests/**
        
jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_VERSION: '8.0.x'

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: 'dotnet build'
      run: dotnet build ContestSolution.sln
